# Generated by Django 4.0.1 on 2022-01-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Login',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name': ''},
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
