# Generated by Django 4.0.1 on 2022-01-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_contact_login_delete_item_alter_login_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
