# Generated by Django 4.0.1 on 2022-01-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
